import type { Metadata } from "next";



import GoogleWraper from "@/components/GoogleWraper";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "My Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={` `}
      > <GoogleWraper>
        <Toaster
        />
        {children}
        </GoogleWraper>
      </body>

    </html>
  );
}
